refactor: minor changes:
edwinhern/express-typescript-2024 pull request #246
Opened 2024-07-24 12:50 UTC by jhz-dev

- Changing the nodejs version to 22.4.1
- Created a dedicated userController to separate the logic from the router

2024-07-25 09:19 UTC, edwinhern commented
Could you fix merge conflicts, thank you!

2024-07-25 09:27 UTC, edwinhern requested changes
LGTM! Just the small change with service class and merge conflict fix

2024-07-25 09:27 UTC, edwinhern commented on src/api/user/userController.ts
> +import { userServiceInstance } from "@/api/user/userService";
Could you update to 'userService'? similar to the userController class. 

Im liking the pascal case for the classes. 😀

2024-07-25 22:39 UTC, edwinhern approved these changes

2024-07-26 05:54 UTC, edwinhern requested changes
Could you update the `userService` test file. We also need to update the Class initialization name

2024-07-26 14:03 UTC, jhz-dev commented
> Could you update the `userService` test file. We also need to update the Class initialization name
> 
> Here's the path: `src/api/user/__tests__/userService.test.ts `

Sure, I will take a look. Thanks

2024-07-28 16:24 UTC, jhz-dev commented
@edwinhern the PR is ready for review now. Let me know if something else is needed. Thanks

2024-07-28 19:48 UTC, edwinhern approved these changes

2024-07-28 19:49 UTC, merged